[project]
name = "beds2bytes-ai-basics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.4.9",
    "jupyterlab-rise>=0.43.1",
    "rise>=5.7.1",
]
